image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1574.84638,    0.     ,  625.71086,
            0.     , 1576.21624,  551.7917 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.075795, 0.188248, -0.000260, 0.000053, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1564.31824,    0.     ,  625.43276,    0.     ,
            0.     , 1566.04846,  551.2119 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]